import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/global/NavBar";
import Footer from "@/components/global/Footer";
import { Toaster } from "@/components/ui/sonner";
import { getCurrentUser } from "@/lib/auth";
import { getCart } from "@/lib/actions";
import AuthProvider from "@/providers/AuthProvider";
import CartHydrator from "@/providers/CartProvider";
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CORA'L ",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();
  const cart = await getCart();
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased flex flex-col min-h-screen`}
      >
        <AuthProvider initialUser={user || null}>
          <CartHydrator initialCart={cart || null}>
            <NavBar />
            <main className="grow">{children}</main>
            <Footer />
            <Toaster />
          </CartHydrator>
        </AuthProvider>
      </body>
    </html>
  );
}
