import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/global/NavBar";
import Footer from "@/components/global/Footer";
import { Toaster } from "@/components/ui/sonner";
import AuthProvider from "@/providers/AuthProvider";
import WishListItemIdsHydrator from "@/providers/WishListItemIdsHydrator";
import CartHydrator from "@/providers/CartProvider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CORA'L ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased flex flex-col min-h-screen`}
      >
        <AuthProvider />
        <CartHydrator initialCart={null}>
          <NavBar />
          <main className="grow">{children}</main>

          <Footer />
        </CartHydrator>
        <Toaster />
        {/* Load wishlist after critical content */}
        <WishListItemIdsHydrator initialWishlistIds={null} />
      </body>
    </html>
  );
}
